<a href="https://colab.research.google.com/github/coezbek/uts-94691-Deep-Learning-2026/blob/main/2026-02-17-DL_Lab1_Exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lab: PyTorch**

In [ ]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Exercise 1: Manipulating Tensors

In this exercise, we will learn how to create tensors using PyTorch

The steps are:
1.   Import PyTorch
2.   Create Scalars
3.   Create Vectors
4.   Create Matrices
5.   Create Tensors
6.   Compatibility with Numpy
7.   Reshape Tensors




### 1. Import PyTorch

**[1.1]** Import PyTorch and numpy packages

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
import torch
import numpy as np

**[1.2]** Print the version of PyTorch

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
torch.__version__

'2.9.0+cu128'

### 2.   Create Scalars

**[2.1]** Create a scalar that will contain the value 4 and name it `scalar1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
scalar1 = torch.tensor(4)
scalar1

tensor(4)

**[2.2]** Print the dimensions of `scalar1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
scalar1.shape

torch.Size([])

**[2.3]** Print the rank of `scalar1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
scalar1.ndim

0

**[2.4]** Print the data type of `scalar1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
scalar1.dtype

torch.int64

**[2.5]** Print the device used by `scalar1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
b = scalar1.device
b

device(type='cpu')

**[2.6]** Change the runtime type by adding GPU as hardware accelerator, run all the previous cells and print the device used now by `scalar1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
b = scalar1.to(device) # Please check that you have an NVIDIA GPU and the driver is installed
b.device

device(type='cuda', index=0)

**[2.7]** Check that NVIDIA driver is correctly installed (https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html#torch.cuda.is_available)

In [ ]:
torch.cuda.is_available() # If returns TRUE that means the NVIDIA driver is correctly installed

True


### 3.   Create Vectors

**[3.1]** Create a vector that will contain the values 2, 3, and 4 and name it `vector1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
vector1 = torch.tensor(
    [2.0, 3.0, 4.0]
)
vector1

tensor([2., 3., 4.])

**[3.2]** Print the dimensions and rank of `vector1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
print(vector1.shape)
print(vector1.ndim)

torch.Size([3])
1


**[3.3]** Print the first element of `vector1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
vector1[0]

tensor(2.)

**[3.4]** Print the elements of `vector1` from the second index

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
vector1[1:]

tensor([3., 4.])

### 4.   Create Matrices

**[4.1]** Create a matrix that will contain the following values and name it `matrix1`: [1, 2], [3, 4], [5, 6]

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
matrix1 = torch.tensor(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ], dtype=torch.float16)
matrix1

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float16)

**[4.2]** Print the dimensions and rank of `matrix1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
print(matrix1.shape)
print(matrix1.ndim)

torch.Size([3, 2])
2


**[4.3]** Print the first dimension of `matrix1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
matrix1[0]

tensor([1., 2.], dtype=torch.float16)

**[4.4]** Print the second element of the first dimension of `matrix1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
matrix1[2][0]

tensor(5., dtype=torch.float16)

**[4.5]** Print the last element of the first dimension of `matrix1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
matrix1[0][-1:]

tensor([2.], dtype=torch.float16)

### 5.   Create Tensors

**[5.1]** Create a tensor called `tensor1` of shape (3, 2, 5) that will have sequential integers from 0 to 29 as values

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
tensor1 = torch.tensor(
    [
      [
          [0, 1, 2, 3, 4],
          [5, 6, 7, 8, 9]
      ],
      [
          [10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19]
      ],
      [
          [20, 21, 22, 23, 24],
          [25, 26, 27, 28, 29]
      ],
    ]
)

tensor1

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])

**[5.2]** Print the dimensions and rank of `tensor1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
print(tensor1.shape)
print(tensor1.ndim)

torch.Size([3, 2, 5])
3


**[5.3]** Print the first dimension of `tensor1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
tensor1[0]

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**[5.4]** Print the second element of the first dimension of `tensor1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
tensor1[0][1]

tensor([5, 6, 7, 8, 9])

**[5.5]** Print the values from the forth index of the second element of the first dimension of `tensor1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
tensor1[0][1][3:]

tensor([8, 9])

### 6.   Compatibility with Numpy

**[6.1]** Convert `tensor1` to a numpy array

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
np.array(tensor1)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

**[6.2]** Convert `tensor1` to a numpy array using `.numpy()`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
tensor1.numpy()

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

### 7.   Reshape Tensors

**[7.1]** Convert the dimensions of `tensor1` to (2, 15)

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
#torch.tensor(tensor1, shape(2, 15))
torch.reshape(tensor1,(2, 15))

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

**[7.2]** Convert the dimensions of `tensor1` to (3, 10)

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
torch.reshape(tensor1, (3, 10))

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

**[7.3]** Convert the dimensions of `tensor1` to (3, 1, 10)

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
torch.reshape(tensor1,(3, 1, 10))

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]])

**[7.4]** Flatten `tensor1`

In [ ]:
# Placeholder for student's code

In [ ]:
# Solution
torch.flatten(tensor1)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])